services:

  music:
    # image: ghcr.io/danielkoomen/webapp
    build:
      context: .
      target: prod
    volumes:
      - type: bind
        source: ./music
        target: /music
      - type: bind
        source: ./data
        target: /data
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 5G
    user: '1000'
    read_only: true
    cap_drop: ['all']
    environment:
      TZ: Europe/Amsterdam
      MUSIC_PROXY_COUNT: 1

  music-nginx:
    # image: ghcr.io/danielkoomen/webapp:nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:8080
    user: '1000'
    environment:
      TZ: Europe/Amsterdam
      BACKEND_ADDRESS: http://music:8080
