FROM nginxinc/nginx-unprivileged

USER root
RUN rm /usr/share/nginx/html/*
USER www-data

COPY --chown=www-data raphson_mp/static /usr/share/nginx/html/static

COPY docker/nginx/default.conf /etc/nginx/conf.d/
COPY docker/nginx/proxy.conf.template /etc/nginx/templates/

RUN cat /usr/share/nginx/html/static/js/player/*.js > /usr/share/nginx/html/static/js/player.js

ENV NGINX_ENVSUBST_OUTPUT_DIR=/tmp
