#!/usr/bin/env bash
set -e
# Start music player in offline mode
# Intended for running music player in Termux environment
source termux/settings
mkdir -p data
pybabel compile -d app/translations
python mp.py start
