#!/usr/bin/env bash
# Start music player in offline mode
# Intended for running music player in Termux environment
set -e
mkdir -p data
pybabel compile -d app/translations
python mp.py --offline --data-dir=./data --short-log-format start $@
