#!/usr/bin/env bash
set -ex
# Start music player in offline mode
# Intended for running music player in Termux environment
source termux/settings
mkdir -p data
cd src
pybabel compile -d translations
python db.py
exec python -m gunicorn -b 127.0.0.1:8080 app:app
